In [2]:

import numpy as np
import math

In [11]:
a=np.array([(123,1.0),(1,2)],dtype=float)
print(a)
print(a.ndim)

[[123.   1.]
 [  1.   2.]]
2


In [11]:
b=np.linspace(5,15,3)
print(b)

[ 5. 10. 15.]


In [6]:
#arange(start,end-1,jump)
print(np.arange(1,16,2))

[ 1  3  5  7  9 11 13 15]


In [14]:
print(np.zeros(5,int))

print(np.ones(5,int))

[0 0 0 0 0]
[1 1 1 1 1]


In [15]:
#add 5 to each element in array
#old format
arr=np.array([1,2,3,4,5])
for i in range(len(arr)):
    arr[i]=arr[i]+5
print(arr)

[ 6  7  8  9 10]


In [16]:
#new format
arr=np.array([1,2,3,4,5])
arr=arr+5
print(arr)

[ 6  7  8  9 10]


In [17]:
#add two arrays

arr1=np.array([1,1,2,5,6,7])
arr2=np.array([6,5,4,3,2,1])
arr3=arr1+arr2
print(arr3)

[7 6 6 8 8 8]


In [18]:
#mathematical operations
arr=np.array([1,2,3,4,5,6])
print(min(arr))
print(sum(arr))
print(sqrt(arr))

1
21


NameError: name 'sqrt' is not defined

In [15]:
#copying one array to another
#1.view() shallow copy

arr=np.array([1,2,3,4,5,6])
arr1=arr.view()#added arr to arr1
#address is same to both arrays
print(id(arr1))
print(id(arr))
#meaning of shalow copy :if u change one value in array then another array will also be changed with that value
arr[1]=10
print(arr1)


#2.copy() quite opposite to view()
#its called deep copy
     #----------------------------------#


2554083698608
2554083741824
[ 1 10  3  4  5  6]
2554083741744
2554083742224
[1 2 3 4 5 6]


In [20]:

#2d array
     
arrr=np.array([[1,2,34],[4,3,2]])
print(arrr)
print(arrr.dtype)
print(arrr.ndim)


[[ 1  2 34]
 [ 4  3  2]]
int32
2


In [21]:
#converting from two dimensional to 1 dimensional
arrr=np.array([[1,2,34],[4,3,2]])
arrr1=arrr.flatten()
print(f"{arrr1} dimen= {arrr1.ndim}")

[ 1  2 34  4  3  2] dimen= 1


In [22]:
#convert 1d array to 2d or 3d .......
arr=np.array([1,2,3,45,5,5])
arr1=arr.reshape(2,3)
print(arr1)

[[ 1  2  3]
 [45  5  5]]


In [24]:
#create matrix using built in function

mat=matrix('1 2 3 ; 4 5 6')
print(mat)


NameError: name 'matrix' is not defined